(custom-set-variables
 '(jde-compiler (quote ("javac server" "")))
 '(jde-jdk (quote ("1.4.2")))
 '(jde-compile-finish-hook (quote (jde-compile-finish-refresh-speedbar jde-compile-finish-flush-completion-cache)))
 '(jde-global-classpath (quote ("/usr/share/java/ant.jar")))
 '(jde-gen-comments nil)
 '(package-get-remote (quote (("ftp.xemacs.org" "/pub/xemacs/packages"))))
 '(jde-jdk-registry (quote (("1.4.2" . "/usr/java/current"))))
 '(jde-ant-build-hook (quote (jde-compile-finish-refresh-speedbar jde-compile-finish-flush-completion-cache)))
 '(jde-launch-beanshell-on-demand-p nil)
 '(jde-ant-read-target t)
 '(package-get-always-update nil)
 '(tab-stop-list (quote (4 8 12 16 20 24 28 32 36 40 48 52 56 60 64 68 72 76 80 84 88 92 96 100 104 108 112 116 120)) t)
 '(tab-width 4)
 '(jde-enable-abbrev-mode nil)
 '(user-full-name "Kenkichi Mahara" t)
 '(jde-ant-enable-find t)
 '(user-mail-address "mahara@mkb.ne.jp")
 '(query-user-mail-address nil)
 '(jde-ant-invocation-method (quote ("Ant Server"))))
(custom-set-faces)
(setq minibuffer-max-depth nil)
; '(jde-run-option-debug (quote (nil "Attach" nil)))
; '(jde-compile-option-target (quote ("1.1")))
; '(jde-compile-option-sourcepath (quote ("/tmp/test2")))
; '(jde-compile-option-classpath (quote ("/tmp/test1")))
; '(jde-compile-option-optimize t)
; (setq jde-compiler '("javac" "/usr/bin/javac"))
; (setq jde-compile-option-sourcepath '("/usr/local/jikes"))

;; (setq jde-build-function '(jde-ant-build))
  ;;   (setq jde-ant-program "/usr/bin/ant")
  ;;   (setq jde-ant-buildfile "build.xml")
  ;;   (setq jde-ant-enable-find t)
  ;;   (setq jde-ant-read-target t)

